//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace istemci.DDService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Kullanici", Namespace="http://schemas.datacontract.org/2004/07/servis.Model")]
    [System.SerializableAttribute()]
    public partial class Kullanici : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AvatarLinkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EpostaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IsimField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int KimlikField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KullaniciAdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool KullaniciTuruField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ParolaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private istemci.DDService.Soru[] SorduguSorularField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SoyisimField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private istemci.DDService.Cevap[] VerdigiCevaplarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private istemci.DDService.Yorum[] YaptigiYorumlarField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AvatarLink {
            get {
                return this.AvatarLinkField;
            }
            set {
                if ((object.ReferenceEquals(this.AvatarLinkField, value) != true)) {
                    this.AvatarLinkField = value;
                    this.RaisePropertyChanged("AvatarLink");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Eposta {
            get {
                return this.EpostaField;
            }
            set {
                if ((object.ReferenceEquals(this.EpostaField, value) != true)) {
                    this.EpostaField = value;
                    this.RaisePropertyChanged("Eposta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Isim {
            get {
                return this.IsimField;
            }
            set {
                if ((object.ReferenceEquals(this.IsimField, value) != true)) {
                    this.IsimField = value;
                    this.RaisePropertyChanged("Isim");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Kimlik {
            get {
                return this.KimlikField;
            }
            set {
                if ((this.KimlikField.Equals(value) != true)) {
                    this.KimlikField = value;
                    this.RaisePropertyChanged("Kimlik");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KullaniciAdi {
            get {
                return this.KullaniciAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.KullaniciAdiField, value) != true)) {
                    this.KullaniciAdiField = value;
                    this.RaisePropertyChanged("KullaniciAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool KullaniciTuru {
            get {
                return this.KullaniciTuruField;
            }
            set {
                if ((this.KullaniciTuruField.Equals(value) != true)) {
                    this.KullaniciTuruField = value;
                    this.RaisePropertyChanged("KullaniciTuru");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Parola {
            get {
                return this.ParolaField;
            }
            set {
                if ((object.ReferenceEquals(this.ParolaField, value) != true)) {
                    this.ParolaField = value;
                    this.RaisePropertyChanged("Parola");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public istemci.DDService.Soru[] SorduguSorular {
            get {
                return this.SorduguSorularField;
            }
            set {
                if ((object.ReferenceEquals(this.SorduguSorularField, value) != true)) {
                    this.SorduguSorularField = value;
                    this.RaisePropertyChanged("SorduguSorular");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Soyisim {
            get {
                return this.SoyisimField;
            }
            set {
                if ((object.ReferenceEquals(this.SoyisimField, value) != true)) {
                    this.SoyisimField = value;
                    this.RaisePropertyChanged("Soyisim");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public istemci.DDService.Cevap[] VerdigiCevaplar {
            get {
                return this.VerdigiCevaplarField;
            }
            set {
                if ((object.ReferenceEquals(this.VerdigiCevaplarField, value) != true)) {
                    this.VerdigiCevaplarField = value;
                    this.RaisePropertyChanged("VerdigiCevaplar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public istemci.DDService.Yorum[] YaptigiYorumlar {
            get {
                return this.YaptigiYorumlarField;
            }
            set {
                if ((object.ReferenceEquals(this.YaptigiYorumlarField, value) != true)) {
                    this.YaptigiYorumlarField = value;
                    this.RaisePropertyChanged("YaptigiYorumlar");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Soru", Namespace="http://schemas.datacontract.org/2004/07/servis.Model")]
    [System.SerializableAttribute()]
    public partial class Soru : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BaslikField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private istemci.DDService.Cevap[] CevaplarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int KimlikField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MetinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private istemci.DDService.Kullanici SoranField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Baslik {
            get {
                return this.BaslikField;
            }
            set {
                if ((object.ReferenceEquals(this.BaslikField, value) != true)) {
                    this.BaslikField = value;
                    this.RaisePropertyChanged("Baslik");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public istemci.DDService.Cevap[] Cevaplar {
            get {
                return this.CevaplarField;
            }
            set {
                if ((object.ReferenceEquals(this.CevaplarField, value) != true)) {
                    this.CevaplarField = value;
                    this.RaisePropertyChanged("Cevaplar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Kimlik {
            get {
                return this.KimlikField;
            }
            set {
                if ((this.KimlikField.Equals(value) != true)) {
                    this.KimlikField = value;
                    this.RaisePropertyChanged("Kimlik");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Metin {
            get {
                return this.MetinField;
            }
            set {
                if ((object.ReferenceEquals(this.MetinField, value) != true)) {
                    this.MetinField = value;
                    this.RaisePropertyChanged("Metin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public istemci.DDService.Kullanici Soran {
            get {
                return this.SoranField;
            }
            set {
                if ((object.ReferenceEquals(this.SoranField, value) != true)) {
                    this.SoranField = value;
                    this.RaisePropertyChanged("Soran");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cevap", Namespace="http://schemas.datacontract.org/2004/07/servis.Model")]
    [System.SerializableAttribute()]
    public partial class Cevap : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int KimlikField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MetinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private istemci.DDService.Soru VerildigiSoruField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private istemci.DDService.Kullanici YazanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private istemci.DDService.Yorum[] YorumlarField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Kimlik {
            get {
                return this.KimlikField;
            }
            set {
                if ((this.KimlikField.Equals(value) != true)) {
                    this.KimlikField = value;
                    this.RaisePropertyChanged("Kimlik");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Metin {
            get {
                return this.MetinField;
            }
            set {
                if ((object.ReferenceEquals(this.MetinField, value) != true)) {
                    this.MetinField = value;
                    this.RaisePropertyChanged("Metin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public istemci.DDService.Soru VerildigiSoru {
            get {
                return this.VerildigiSoruField;
            }
            set {
                if ((object.ReferenceEquals(this.VerildigiSoruField, value) != true)) {
                    this.VerildigiSoruField = value;
                    this.RaisePropertyChanged("VerildigiSoru");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public istemci.DDService.Kullanici Yazan {
            get {
                return this.YazanField;
            }
            set {
                if ((object.ReferenceEquals(this.YazanField, value) != true)) {
                    this.YazanField = value;
                    this.RaisePropertyChanged("Yazan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public istemci.DDService.Yorum[] Yorumlar {
            get {
                return this.YorumlarField;
            }
            set {
                if ((object.ReferenceEquals(this.YorumlarField, value) != true)) {
                    this.YorumlarField = value;
                    this.RaisePropertyChanged("Yorumlar");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Yorum", Namespace="http://schemas.datacontract.org/2004/07/servis.Model")]
    [System.SerializableAttribute()]
    public partial class Yorum : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int KimlikField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MetinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private istemci.DDService.Kullanici YapanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private istemci.DDService.Cevap YapildigiCevapField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Kimlik {
            get {
                return this.KimlikField;
            }
            set {
                if ((this.KimlikField.Equals(value) != true)) {
                    this.KimlikField = value;
                    this.RaisePropertyChanged("Kimlik");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Metin {
            get {
                return this.MetinField;
            }
            set {
                if ((object.ReferenceEquals(this.MetinField, value) != true)) {
                    this.MetinField = value;
                    this.RaisePropertyChanged("Metin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public istemci.DDService.Kullanici Yapan {
            get {
                return this.YapanField;
            }
            set {
                if ((object.ReferenceEquals(this.YapanField, value) != true)) {
                    this.YapanField = value;
                    this.RaisePropertyChanged("Yapan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public istemci.DDService.Cevap YapildigiCevap {
            get {
                return this.YapildigiCevapField;
            }
            set {
                if ((object.ReferenceEquals(this.YapildigiCevapField, value) != true)) {
                    this.YapildigiCevapField = value;
                    this.RaisePropertyChanged("YapildigiCevap");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DDService.IDDService")]
    public interface IDDService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDDService/KullaniciKayitEt", ReplyAction="http://tempuri.org/IDDService/KullaniciKayitEtResponse")]
        bool KullaniciKayitEt(string ePosta, string kullaniciAdi, string parola);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDDService/KullaniciKayitEt", ReplyAction="http://tempuri.org/IDDService/KullaniciKayitEtResponse")]
        System.Threading.Tasks.Task<bool> KullaniciKayitEtAsync(string ePosta, string kullaniciAdi, string parola);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDDService/KullaniciGirisiYap", ReplyAction="http://tempuri.org/IDDService/KullaniciGirisiYapResponse")]
        int KullaniciGirisiYap(string kullaniciAdi, string parola);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDDService/KullaniciGirisiYap", ReplyAction="http://tempuri.org/IDDService/KullaniciGirisiYapResponse")]
        System.Threading.Tasks.Task<int> KullaniciGirisiYapAsync(string kullaniciAdi, string parola);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDDService/KullaniciBilgileriniGetir", ReplyAction="http://tempuri.org/IDDService/KullaniciBilgileriniGetirResponse")]
        istemci.DDService.Kullanici KullaniciBilgileriniGetir(int kimlik);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDDService/KullaniciBilgileriniGetir", ReplyAction="http://tempuri.org/IDDService/KullaniciBilgileriniGetirResponse")]
        System.Threading.Tasks.Task<istemci.DDService.Kullanici> KullaniciBilgileriniGetirAsync(int kimlik);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDDService/KullaniciBilgileriniGuncelle", ReplyAction="http://tempuri.org/IDDService/KullaniciBilgileriniGuncelleResponse")]
        bool KullaniciBilgileriniGuncelle(int kimlik, string ePosta, string isim, string soyisim, string parola, string avatarLink);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDDService/KullaniciBilgileriniGuncelle", ReplyAction="http://tempuri.org/IDDService/KullaniciBilgileriniGuncelleResponse")]
        System.Threading.Tasks.Task<bool> KullaniciBilgileriniGuncelleAsync(int kimlik, string ePosta, string isim, string soyisim, string parola, string avatarLink);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDDServiceChannel : istemci.DDService.IDDService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DDServiceClient : System.ServiceModel.ClientBase<istemci.DDService.IDDService>, istemci.DDService.IDDService {
        
        public DDServiceClient() {
        }
        
        public DDServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DDServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DDServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DDServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool KullaniciKayitEt(string ePosta, string kullaniciAdi, string parola) {
            return base.Channel.KullaniciKayitEt(ePosta, kullaniciAdi, parola);
        }
        
        public System.Threading.Tasks.Task<bool> KullaniciKayitEtAsync(string ePosta, string kullaniciAdi, string parola) {
            return base.Channel.KullaniciKayitEtAsync(ePosta, kullaniciAdi, parola);
        }
        
        public int KullaniciGirisiYap(string kullaniciAdi, string parola) {
            return base.Channel.KullaniciGirisiYap(kullaniciAdi, parola);
        }
        
        public System.Threading.Tasks.Task<int> KullaniciGirisiYapAsync(string kullaniciAdi, string parola) {
            return base.Channel.KullaniciGirisiYapAsync(kullaniciAdi, parola);
        }
        
        public istemci.DDService.Kullanici KullaniciBilgileriniGetir(int kimlik) {
            return base.Channel.KullaniciBilgileriniGetir(kimlik);
        }
        
        public System.Threading.Tasks.Task<istemci.DDService.Kullanici> KullaniciBilgileriniGetirAsync(int kimlik) {
            return base.Channel.KullaniciBilgileriniGetirAsync(kimlik);
        }
        
        public bool KullaniciBilgileriniGuncelle(int kimlik, string ePosta, string isim, string soyisim, string parola, string avatarLink) {
            return base.Channel.KullaniciBilgileriniGuncelle(kimlik, ePosta, isim, soyisim, parola, avatarLink);
        }
        
        public System.Threading.Tasks.Task<bool> KullaniciBilgileriniGuncelleAsync(int kimlik, string ePosta, string isim, string soyisim, string parola, string avatarLink) {
            return base.Channel.KullaniciBilgileriniGuncelleAsync(kimlik, ePosta, isim, soyisim, parola, avatarLink);
        }
    }
}
