//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace İstemci.DDService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DDService.IDDService")]
    public interface IDDService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDDService/KullaniciKayitEt", ReplyAction="http://tempuri.org/IDDService/KullaniciKayitEtResponse")]
        bool KullaniciKayitEt(string ePosta, string kullaniciAdi, string parola);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDDService/KullaniciKayitEt", ReplyAction="http://tempuri.org/IDDService/KullaniciKayitEtResponse")]
        System.Threading.Tasks.Task<bool> KullaniciKayitEtAsync(string ePosta, string kullaniciAdi, string parola);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDDService/KullaniciGirisiYap", ReplyAction="http://tempuri.org/IDDService/KullaniciGirisiYapResponse")]
        bool KullaniciGirisiYap(string kullaniciAdi, string parola);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDDService/KullaniciGirisiYap", ReplyAction="http://tempuri.org/IDDService/KullaniciGirisiYapResponse")]
        System.Threading.Tasks.Task<bool> KullaniciGirisiYapAsync(string kullaniciAdi, string parola);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDDServiceChannel : İstemci.DDService.IDDService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DDServiceClient : System.ServiceModel.ClientBase<İstemci.DDService.IDDService>, İstemci.DDService.IDDService {
        
        public DDServiceClient() {
        }
        
        public DDServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DDServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DDServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DDServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool KullaniciKayitEt(string ePosta, string kullaniciAdi, string parola) {
            return base.Channel.KullaniciKayitEt(ePosta, kullaniciAdi, parola);
        }
        
        public System.Threading.Tasks.Task<bool> KullaniciKayitEtAsync(string ePosta, string kullaniciAdi, string parola) {
            return base.Channel.KullaniciKayitEtAsync(ePosta, kullaniciAdi, parola);
        }
        
        public bool KullaniciGirisiYap(string kullaniciAdi, string parola) {
            return base.Channel.KullaniciGirisiYap(kullaniciAdi, parola);
        }
        
        public System.Threading.Tasks.Task<bool> KullaniciGirisiYapAsync(string kullaniciAdi, string parola) {
            return base.Channel.KullaniciGirisiYapAsync(kullaniciAdi, parola);
        }
    }
}
