//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace servis.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cevap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cevap()
        {
            this.Yorum = new HashSet<Yorum>();
        }
    
        public int Kimlik { get; set; }
        public string Metin { get; set; }
        public System.DateTime CevaplamaTarihi { get; set; }
        public Nullable<int> VerildigiSoru_Kimlik { get; set; }
        public Nullable<int> Yazan_Kimlik { get; set; }
        public bool OnayDurumu { get; set; }
    
        public virtual Kullanici Kullanici { get; set; }
        public virtual Soru Soru { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Yorum> Yorum { get; set; }
    }
}
