//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace servis.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DDBEntities : DbContext
    {
        public DDBEntities()
            : base("name=DDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cevap> Cevap { get; set; }
        public virtual DbSet<Kullanici> Kullanici { get; set; }
        public virtual DbSet<Soru> Soru { get; set; }
        public virtual DbSet<Yorum> Yorum { get; set; }
        public virtual DbSet<FavoriCevaplar> FavoriCevaplar { get; set; }
        public virtual DbSet<FavoriSorular> FavoriSorular { get; set; }
    }
}
