//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace servis.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FavoriCevaplar
    {
        public int KullaniciKimlik { get; set; }
        public int CevapKimlik { get; set; }
    }
}
